"""watchlists and intelligence events

Revision ID: 7969db20724a
Revises: 0005_radar
Create Date: 2026-07-30 09:37:52.877607
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7969db20724a"
down_revision: str | None = "0005_radar"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyst_reading_cache",
        sa.Column("mint_address", sa.String(length=44), nullable=False),
        sa.Column("mission_state", sa.String(length=32), nullable=True),
        sa.Column("research_priority", sa.String(length=16), nullable=True),
        sa.Column("combined_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("liquidity_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("momentum_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("risk_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("clone_risk", sa.String(length=16), nullable=True),
        sa.Column("exit_severity", sa.String(length=16), nullable=True),
        sa.Column(
            "warning_codes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyst_reading_cache")),
        sa.UniqueConstraint(
            "mint_address", name=op.f("uq_analyst_reading_cache_mint_address")
        ),
    )
    op.create_index(
        "ix_reading_cache_observed",
        "analyst_reading_cache",
        [sa.literal_column("observed_at DESC")],
        unique=False,
    )
    op.create_table(
        "intelligence_events",
        sa.Column("mint_address", sa.String(length=44), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "mission_promoted",
                "mission_downgraded",
                "priority_increased",
                "priority_decreased",
                "risk_increased",
                "risk_resolved",
                "clone_detected",
                "clone_resolved",
                "liquidity_improved",
                "liquidity_weakened",
                "momentum_weakened",
                "momentum_improved",
                "exit_watch_activated",
                "exit_watch_cleared",
                "confidence_increased",
                "confidence_decreased",
                "first_analysed",
                name="event_kind",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("info", "notable", "urgent", name="event_severity"),
            nullable=False,
        ),
        sa.Column("analyst", sa.String(length=16), nullable=True),
        sa.Column("previous_value", sa.String(length=64), nullable=True),
        sa.Column("current_value", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.String(length=400), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intelligence_events")),
        sa.UniqueConstraint(
            "mint_address", "kind", "occurred_at", name="uq_events_mint_kind_at"
        ),
    )
    op.create_index(
        "ix_events_mint_occurred",
        "intelligence_events",
        ["mint_address", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_events_occurred",
        "intelligence_events",
        [sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_table(
        "watchlists",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=280), nullable=True),
        sa.Column(
            "alert_on",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_watchlists_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlists")),
        sa.UniqueConstraint("user_id", "name", name="uq_watchlists_user_name"),
    )
    op.create_index(
        op.f("ix_watchlists_created_at"), "watchlists", ["created_at"], unique=False
    )
    op.create_index("ix_watchlists_user", "watchlists", ["user_id"], unique=False)
    op.create_table(
        "watchlist_items",
        sa.Column("watchlist_id", sa.UUID(), nullable=False),
        sa.Column("mint_address", sa.String(length=44), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("added_mission_state", sa.String(length=32), nullable=True),
        sa.Column("added_priority", sa.String(length=16), nullable=True),
        sa.Column("added_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlists.id"],
            name=op.f("fk_watchlist_items_watchlist_id_watchlists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_items")),
        sa.UniqueConstraint("watchlist_id", "mint_address", name="uq_watchlist_items_mint"),
    )
    op.create_index(
        op.f("ix_watchlist_items_created_at"), "watchlist_items", ["created_at"], unique=False
    )
    op.create_index(
        "ix_watchlist_items_list", "watchlist_items", ["watchlist_id"], unique=False
    )
    op.create_index(
        "ix_watchlist_items_mint", "watchlist_items", ["mint_address"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_watchlist_items_mint", table_name="watchlist_items")
    op.drop_index("ix_watchlist_items_list", table_name="watchlist_items")
    op.drop_index(op.f("ix_watchlist_items_created_at"), table_name="watchlist_items")
    op.drop_table("watchlist_items")
    op.drop_index("ix_watchlists_user", table_name="watchlists")
    op.drop_index(op.f("ix_watchlists_created_at"), table_name="watchlists")
    op.drop_table("watchlists")
    op.drop_index("ix_events_occurred", table_name="intelligence_events")
    op.drop_index("ix_events_mint_occurred", table_name="intelligence_events")
    op.drop_table("intelligence_events")
    op.drop_index("ix_reading_cache_observed", table_name="analyst_reading_cache")
    op.drop_table("analyst_reading_cache")
    # ### end Alembic commands ###
