"""Radar opportunity tracking.

Adds the three Opportunity Radar tables. Purely additive: no existing table,
column, index or constraint is touched, so the launch scanner and the scoring
engine are unaffected and this can be applied while they run.

`ix_refresh_tokens_expires_at` is deliberately NOT dropped here. Autogenerate
proposes removing it because the index exists in the database (migration 0001)
but not in the model — pre-existing drift recorded in §13 of the master
context. Correcting it belongs in its own migration, not smuggled into a
feature change where nobody would look for it.

Revision ID: 0005_radar
Revises: 0004_ai_scoring
Create Date: 2026-07-29 07:50:23.826472
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005_radar"
down_revision: str | None = "0004_ai_scoring"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "radar_tokens",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("mint_address", sa.String(length=44), nullable=False),
        sa.Column(
            "first_detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("first_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("first_market_cap", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("first_liquidity", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("first_volume_24h", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("first_holder_count", sa.Integer(), nullable=True),
        sa.Column("first_opportunity_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("first_confidence", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "detection_reason",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("current_market_cap", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("current_liquidity", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column(
            "current_opportunity_score", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("current_confidence", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("current_category", sa.String(length=32), nullable=False),
        sa.Column("peak_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("peak_market_cap", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("peak_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("peak_multiple", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("current_multiple", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column(
            "last_evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["discovered_tokens.id"],
            name=op.f("fk_radar_tokens_token_id_discovered_tokens"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_radar_tokens")),
        sa.UniqueConstraint("mint_address", name=op.f("uq_radar_tokens_mint_address")),
    )
    op.create_index(
        "ix_radar_tokens_category", "radar_tokens", ["current_category"], unique=False
    )
    op.create_index(
        "ix_radar_tokens_detected", "radar_tokens", ["first_detected_at"], unique=False
    )
    op.create_index(
        "ix_radar_tokens_peak_multiple",
        "radar_tokens",
        ["peak_multiple"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "ix_radar_tokens_score", "radar_tokens", ["current_opportunity_score"], unique=False
    )
    op.create_table(
        "radar_achievements",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("radar_token_id", sa.UUID(), nullable=False),
        sa.Column("mint_address", sa.String(length=44), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("multiple", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column(
            "achieved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("price_at_achievement", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column(
            "market_cap_at_achievement", sa.Numeric(precision=24, scale=4), nullable=True
        ),
        sa.Column("days_to_achieve", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["radar_token_id"],
            ["radar_tokens.id"],
            name=op.f("fk_radar_achievements_radar_token_id_radar_tokens"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_radar_achievements")),
        sa.UniqueConstraint("radar_token_id", "tier", name="uq_radar_achievement_tier"),
    )
    op.create_index("ix_radar_achievements_tier", "radar_achievements", ["tier"], unique=False)
    op.create_index(
        "ix_radar_achievements_time", "radar_achievements", ["achieved_at"], unique=False
    )
    op.create_table(
        "radar_snapshots",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("radar_token_id", sa.UUID(), nullable=False),
        sa.Column("mint_address", sa.String(length=44), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("market_cap", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("liquidity", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("volume_24h", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("holder_count", sa.Integer(), nullable=True),
        sa.Column("opportunity_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("coverage", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column(
            "dimensions",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "reasons",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["radar_token_id"],
            ["radar_tokens.id"],
            name=op.f("fk_radar_snapshots_radar_token_id_radar_tokens"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_radar_snapshots")),
    )
    op.create_index(
        "ix_radar_snapshots_mint_time",
        "radar_snapshots",
        ["mint_address", "captured_at"],
        unique=False,
    )
    op.create_index(
        "ix_radar_snapshots_token_time",
        "radar_snapshots",
        ["radar_token_id", "captured_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_radar_snapshots_token_time", table_name="radar_snapshots")
    op.drop_index("ix_radar_snapshots_mint_time", table_name="radar_snapshots")
    op.drop_table("radar_snapshots")
    op.drop_index("ix_radar_achievements_time", table_name="radar_achievements")
    op.drop_index("ix_radar_achievements_tier", table_name="radar_achievements")
    op.drop_table("radar_achievements")
    op.drop_index("ix_radar_tokens_score", table_name="radar_tokens")
    op.drop_index(
        "ix_radar_tokens_peak_multiple",
        table_name="radar_tokens",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index("ix_radar_tokens_detected", table_name="radar_tokens")
    op.drop_index("ix_radar_tokens_category", table_name="radar_tokens")
    op.drop_table("radar_tokens")
    # ### end Alembic commands ###
